### ISSUE TITLE
App distribution

### ISSUE THREAD

**Issue by vishal377** [ashar-7/ScreenTrack-Android#2]
Hi I want to publish this app on the Google play store
According to the license I can do that but still want to ask you.... should I do that ?

**Comment by ashar-7** [comment]
You can't publish the exact app but you can make some changes to the app and then publish it

**Comment by vishal377** [comment]
Yes, I am gonna put a small new feature in the settings and gonna publish it soon

**Comment by ashar-7** [comment]
Alright
